"""Write the R package's help files (r/man/*.Rd) from the #' comments in r/R/*.R.

A small stand-in for roxygen2, enough for the tags this package uses (@param, @return, @examples,
@export, @rdname, @seealso, @noRd), so the help pages can be regenerated without installing anything:

    python packaging/rd.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _rd_text(text: str) -> str:
    text = text.replace("\\", "\\\\").replace("%", "\\%").replace("{", "\\{").replace("}", "\\}")
    text = re.sub(r"\[([A-Za-z_.]+)\(\)\]", r"\\code{\\link{\1}}", text)
    return re.sub(r"`([^`]+)`", r"\\code{\1}", text)


def blocks(source: str):
    """(comment lines, the function name, its signature) for every documented function."""
    lines = source.splitlines()
    i = 0
    while i < len(lines):
        if lines[i].startswith("#'"):
            comment = []
            while i < len(lines) and lines[i].startswith("#'"):
                comment.append(lines[i][2:].removeprefix(" "))
                i += 1
            head = lines[i] if i < len(lines) else ""
            m = re.match(r"^([\w.]+)\s*<-\s*function\s*\(", head)
            if m:
                sig, depth = "", 0
                text = "\n".join(lines[i:i + 20])
                start = text.index("function") + len("function")
                for ch in text[start:]:
                    sig += ch
                    depth += ch == "("
                    depth -= ch == ")"
                    if depth == 0 and sig.strip():
                        break
                yield comment, m.group(1), " ".join(sig.split())
        else:
            i += 1


def parse(comment):
    doc = {"title": "", "description": [], "params": [], "return": "", "examples": [], "rdname": "",
           "seealso": "", "noRd": False}
    tag, paragraph = None, []
    for line in comment:
        m = re.match(r"^@(\w+)\s*(.*)$", line)
        if m:
            tag, rest = m.group(1), m.group(2)
            if tag == "param":
                name, _, text = rest.partition(" ")
                doc["params"].append([name, text])
            elif tag in ("return", "seealso", "rdname"):
                doc[tag] = rest
            elif tag == "noRd":
                doc["noRd"] = True
            continue
        if tag is None:
            if not doc["title"]:
                doc["title"] = line
            else:
                paragraph.append(line)
        elif tag == "param":
            doc["params"][-1][1] += " " + line.strip()
        elif tag in ("return", "seealso"):
            doc[tag] += " " + line.strip()
        elif tag == "examples":
            doc["examples"].append(line)
    doc["description"] = "\n".join(paragraph).strip()
    return doc


def usage(name: str, sig: str) -> str:
    if name.count(".") and name.split(".")[0] in ("print", "summary", "as"):
        generic, _, cls = name.partition(".")
        if generic == "as":
            generic, cls = "as.matrix", name.split(".", 2)[2]
        return f"\\method{{{generic}}}{{{cls}}}{sig}"
    return f"{name}{sig}"


def main() -> int:
    pages = {}
    for path in sorted((ROOT / "r" / "R").glob("*.R")):
        for comment, name, sig in blocks(path.read_text(encoding="utf-8")):
            doc = parse(comment)
            if doc["noRd"]:
                continue
            page = doc["rdname"] or name
            entry = pages.setdefault(page, {"doc": doc, "names": [], "usages": [], "params": []})
            entry["names"].append(name)
            entry["usages"].append(usage(name, sig))
            entry["params"] += [p for p in doc["params"] if p[0] not in {q[0] for q in entry["params"]}]
    out_dir = ROOT / "r" / "man"
    out_dir.mkdir(exist_ok=True)
    for old in out_dir.glob("*.Rd"):
        old.unlink()
    for page, entry in pages.items():
        doc = entry["doc"]
        parts = ["% Generated by packaging/rd.py from r/R: do not edit by hand", f"\\name{{{page}}}"]
        parts += [f"\\alias{{{n}}}" for n in entry["names"]]
        parts += [f"\\title{{{_rd_text(doc['title'])}}}", "\\usage{", *entry["usages"], "}"]
        if entry["params"]:
            parts.append("\\arguments{")
            parts += [f"\\item{{{n}}}{{{_rd_text(t.strip())}}}" for n, t in entry["params"]]
            parts.append("}")
        if doc["return"]:
            parts.append(f"\\value{{{_rd_text(doc['return'].strip())}}}")
        parts.append(f"\\description{{\n{_rd_text(doc['description'] or doc['title'])}\n}}")
        if doc["seealso"]:
            parts.append(f"\\seealso{{{_rd_text(doc['seealso'].strip())}}}")
        if doc["examples"]:
            parts += ["\\examples{", *doc["examples"], "}"]
        (out_dir / f"{page}.Rd").write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"wrote {len(pages)} help page(s) to r/man")
    return 0


if __name__ == "__main__":
    sys.exit(main())
